### ISSUE TITLE
Warnings when using PHP 8

### ISSUE THREAD

**Issue by nclavaud** [bpolaszek/bentools-etl#7]
Hi :wave:

Thank you very much for this lib. I managed to implement a full, custom ETL workflow and all went smoothly.

Using PHP 8, I got those two warnings, though:
```
PHP Warning:  "resource" is not a supported builtin type and will be interpreted as a class name. Write "\Safe\resource" or import the class with "use" to suppress this warning in vendor/thecodingmachine/safe/generated/sockets.php on line 797
PHP Warning:  "integer" will be interpreted as a class name. Did you mean "int"? Write "\Safe\integer" or import the class with "use" to suppress this warning in vendor/thecodingmachine/safe/generated/swoole.php on line 17
```

I guess this is because the referenced version of the `thecodingmachine/safe` lib is quite old.

**Comment by pablomadariaga** [comment]
Hello I am having the same problem in laravel v9.24.0 with PHP 8.1.9 in August 2022
![image](https://user-images.githubusercontent.com/69119357/183769848-db354b42-8d52-4ca1-b3d3-63c989a0d7aa.png)

**Comment by bpolaszek** [comment]
Hello 👋 

It's been a while I didn't work on this library - are you using version 2.x or 3.x? I'll have a look as soon as possible.

**Comment by bpolaszek** [comment]
What version of this library are you using?

**Comment by pablomadariaga** [comment]
Hi, I'm Sorry.
![image](https://user-images.githubusercontent.com/69119357/184140586-a2a12d1c-118f-4001-a828-dd98fe2dfdac.png)

**Comment by bpolaszek** [comment]
I was speaking about `bentools/etl` actually 🙂

**Comment by cortierdev** [comment]
Anybody? I just updated Laravel and this warning shows up on every php artisan command.

**Comment by bpolaszek** [comment]
> Anybody? I just updated Laravel and this warning shows up on every php artisan command.

What version of `bentools/etl` are you using?

**Comment by ssabit** [comment]
Solution for 1: Open vendor/thecodingmachine/sockets.php in line number 4 add
`use resource;`

Solution for 2: Open vendor/thecodingmachine/swoole.php in line number 17 replace ''
`swoole_async_write(string $filename, string $content, int $offset = null, callable $callback = null): void`
 insted of `swoole_async_write(string $filename, string $content, integer $offset = null, callable $callback = null): void`

This will fix your problem! :) @nclavaud

**Comment by olorunda** [comment]
> Hello I am having the same problem in laravel v9.24.0 with PHP 8.1.9 in August 2022 ![image](https://user-images.githubusercontent.com/69119357/183769848-db354b42-8d52-4ca1-b3d3-63c989a0d7aa.png)



> Solution for 1: Open vendor/thecodingmachine/sockets.php in line number 4 add `use resource;`
> 
> Solution for 2: Open vendor/thecodingmachine/swoole.php in line number 17 replace '' `swoole_async_write(string $filename, string $content, int $offset = null, callable $callback = null): void` insted of `swoole_async_write(string $filename, string $content, integer $offset = null, callable $callback = null): void`
> 
> This will fix your problem! :) @nclavaud

Not recommended to directly edit your vendor file .

Here is how i fix this issue  :

Step One :  delete your composer.lock

Step Two : run `composer require thecodingmachine/safe`

This should solve the issue

**Comment by JBOnlinebouwers** [comment]
> > Hello I am having the same problem in laravel v9.24.0 with PHP 8.1.9 in August 2022 ![image](https://user-images.githubusercontent.com/69119357/183769848-db354b42-8d52-4ca1-b3d3-63c989a0d7aa.png)
> 
> > Solution for 1: Open vendor/thecodingmachine/sockets.php in line number 4 add `use resource;`
> > Solution for 2: Open vendor/thecodingmachine/swoole.php in line number 17 replace '' `swoole_async_write(string $filename, string $content, int $offset = null, callable $callback = null): void` insted of `swoole_async_write(string $filename, string $content, integer $offset = null, callable $callback = null): void`
> > This will fix your problem! :) @nclavaud
> 
> Not recommended to directly edit your vendor file .
> 
> Here is how i fix this issue :
> 
> Step One : delete your composer.lock
> 
> Step Two : run `composer require thecodingmachine/safe`
> 
> This should solve the issue

Thank you! This worked for me! I have php version 8.1.10
